### ISSUE TITLE
node not found from cwd in coverage.sh

### ISSUE THREAD

**Issue by CurryKitten** [addaleax/node-core-coverage#21]
Running the latest version of coverage.sh, there seems to be an issue with running node form the current directory.  In line 48-51

```
cd "$SRCDIR"

# get nyc + istanbul-merge
./node "$WORKDIR/node/deps/npm" install
```

There's no node within $SRCDIR, so we fail.  This change went in as your change in the migration from istanbul to nyc, but presumably you didn't want to explicitly use the cwd path

**Comment by addaleax** [comment]
Thanks for reporting, #22 should fix this.
