### ISSUE TITLE
Fix #22 doesn't find node binary still

### ISSUE THREAD

**Issue by CurryKitten** [addaleax/node-core-coverage#23]
It looks like fix #22 doesn't quite address the problem of running the node binary.  The new path of node attempts to run

`"$WORKDIR/node" "$WORKDIR/node/deps/npm" install`

But $WORKDIR/node is a directory, so we'd need `$WORKDIR/node/node`, or just `node` to pick it up of the path you added to earlier in the script

**Comment by addaleax** [comment]
heh, yes, sorry… btw, feel free to make pull requests here yourself! :)

**Comment by CurryKitten** [comment]
Yes, apologies for raising issues instead of making pull requests.  I just need to get a few corporate tick boxes sorted out and I will do.

**Comment by addaleax** [comment]
@CurryKitten Nothing to apologize for! Just thought that might be easier for you, too :)
